### ISSUE TITLE
links dead 

### ISSUE THREAD

**Issue by ABDOELSHEMY** [AlanZhang1995/TwoStreamSR#1]
hi @AlanZhang1995 
thanks for your great work 
could you please re upload the well-trained model to google drive

**Comment by AlanZhang1995** [comment]
> hi @AlanZhang1995
> thanks for your great work
> could you please re upload the well-trained model to google drive

Thank you for your interests in our work. Please try the following link for model.
https://drive.google.com/drive/folders/12THb8Jf5IaHU6V0zADVbMZbU1SGqJs0B?usp=sharing

I will re-upload the other data such as CDVL134 dataset to google drive later and update the link.

**Comment by ABDOELSHEMY** [comment]
work great, Thanks for your quick help

**Comment by ABDOELSHEMY** [comment]
### **Failed to find a checkpoint**
sorry for that, I have successfully tried SoSR and every thing is ok, But when I tried to try ToSR I encountered this error

PS G:\Sr\TwoStreamSR\TwoStreamSR-master\ToSR\step2_train&test\test> python test.py 16 L
WARNING:tensorflow:From G:\Sr\TwoStreamSR\TwoStreamSR-master\ToSR\step2_train&test\test\nets.py:52: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-12 18:19:32.148967: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
Traceback (most recent call last):
  File "test.py", line 170, in <module>
    frames_padded = np.lib.pad(frames, pad_width=((T_in//2,T_in//2),(0,0),(0,0),(0,0)), mode='constant')
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\arraypad.py", line 1172, in pad
    pad_width = _as_pairs(pad_width, narray.ndim, as_index=True)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\arraypad.py", line 953, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\stride_tricks.py", line 129, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,2) and requested shape (1,2)

**Comment by AlanZhang1995** [comment]
> work great, Thanks for your quick help

Hi, I received an email about your question but can't find a record in this issue. 
Is your problem solved？

**Comment by ABDOELSHEMY** [comment]
Thanks for your consideration, and Sorry to waste your time

Actually no, everything works well with SoSR, But when trying to use ToSR I always see this error, when i look at VSR-DUF i found it use Python 2.7

I think because of the Python version that I use
**windows 10
Python 3.6.8
tensorflow 1.5.0**

PS G:\Sr\TwoStreamSR\TwoStreamSR-master\ToSR\step2_train&test\test> python test.py 16 L
WARNING:tensorflow:From G:\Sr\TwoStreamSR\TwoStreamSR-master\ToSR\step2_train&test\test\nets.py:52: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-13 06:18:30.901233: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2

 **[*] Reading checkpoints...
 [*] Failed to find a checkpoint**
Traceback (most recent call last):
  File "test.py", line 170, in <module>
    frames_padded = np.lib.pad(frames, pad_width=((T_in//2,T_in//2),(0,0),(0,0),(0,0)), mode='constant')

  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\arraypad.py", line 1172, in pad
    pad_width = _as_pairs(pad_width, narray.ndim, as_index=True)

  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\arraypad.py", line 953, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()

  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)

  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\stride_tricks.py", line 129, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')
### **ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,2) and requested shape (1,2)**

i put the pre trained model into './ToSR/step2_train&test/test/TFoutput/model'
Any ideas please

**Comment by AlanZhang1995** [comment]
@ABDOELSHEMY 
I find there seems two questions in your log.
The first is 'Failed to find a checkpoint'. Please make sure the 'checkpoint' file is put into the following folder: ".\ToSR\step2_train&test\test\TFoutput\model\VSR-DUF\". This path is defined as 'checkpoint_dir' in line 42.

For the second question, I ran this code with Python 2.7 and TensorFlow 0.4.0 
Since I do not have computer at this time, I cannot check whether this code can run in your environment immediately. If you have anaconda, please build a new environment and try again.

**Comment by ABDOELSHEMY** [comment]
@AlanZhang1995 
ok, thanks for your advice
now the checkpoint is found,  I think it should be changed in readme to ( Please put our well-trained model into './ToSR/step2_train&test/test/TFoutput/model\VSR-DUF') dir

But I found another questions، Record it just for you to consider when you find some time if you like

python test.py 16 L
WARNING:tensorflow:From G:\Sr\TwoStreamSR\TwoStreamSR-master\ToSR\step2_train&test\test\nets.py:52: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-13 13:48:52.559950: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
 [*] Reading checkpoints...
 **[*] Success to read VSR-DUF.model-214601**
Traceback (most recent call last):
  **File "test.py", line 170, in <module>**
    frames_padded = np.lib.pad(frames, pad_width=((T_in//2,T_in//2),(0,0),(0,0),(0,0)), mode='constant')
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\arraypad.py", line 1172, in pad
    pad_width = _as_pairs(pad_width, narray.ndim, as_index=True)

  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\arraypad.py", line 953, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()

  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)

  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\stride_tricks.py", line 129, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')

**ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,2) and requested shape (1,2)**
